<?php 
include 'Affiliate.php';
include 'Customer.php';
include 'Order.php';
include 'StoreOwner.php';
    $Moyes=new StoreOwner();
    $Moyes->setName('Moyes');
    // echo $Moyes->getName();
    $John=new Affiliate();
    $John->setName('John');
    // echo $John->getName();
    $customer1=new Customers();
    $customer2=new Customers();
    $customer3=new Customers();
    $customer4=new Customers();
    $Sarah=new Affiliate();
    $Sarah->setName('Sarah');
    $Sarah->setUpperAffiliate('John');
    $Eva=new Affiliate();
    $Eva->setName('Eva');
    $Eva->setUpperAffiliate('John');
    $Jimmy=new Affiliate();
    $Jimmy->setName('Jimmy');
    $Jimmy->setUpperAffiliate('John');
    $Henry=new Affiliate();
    $Henry->setName('Henry');
    $Henry->setUpperAffiliate('John');
    // echo $Henry->PrintCustomers();
    $Oder=new Order();
    $Oder->setTotal(800);
    $customer1->setAffiliate($Sarah->getName());
    $customer1->PlasceOrder($Oder,$Sarah,$Moyes);
    $customer2->PlasceOrder($Oder,$Eva,$Moyes);
    $customer3->PlasceOrder($Oder,$Jimmy,$Moyes);
    $customer4->PlasceOrder($Oder,$Henry,$Moyes);
    $Sarah->Refer($customer1);
    $John->Refer($Sarah);
    $Eva->Refer($customer2);
    $John->Refer($Eva);
    $Jimmy->Refer($customer3);
    $John->Refer($Jimmy);
    $Henry->Refer($customer4);
    $John->Refer($Henry);
    $John->PrintSubAff();
    $John->Withdraw(300);
    echo "<br>";
    $John->Withdraw(150);
    echo "<br>";
    $John->Withdraw(50);
    echo "<br>";
    $Moyes->Print_balance();
?>